### ISSUE TITLE
字典或许需要更新到E0509,本人已完成字典提取,同学是否有联系方式详聊一下

### ISSUE THREAD

**Issue by R-YaTian** [UMRnInside/njit8021xclient#2]

**Comment by UMRnInside** [comment]
我的字典不就是E0509吗……
话说您是这边（怡山校区/至诚学院）的学生？

**Comment by R-YaTian** [comment]
> 我的字典不就是E0509吗……
> 话说您是这边（怡山校区/至诚学院）的学生？

是的

**Comment by R-YaTian** [comment]
> 我的字典不就是E0509吗……
> 话说您是这边（怡山校区/至诚学院）的学生？

我仔细看了下还真是和我提取的一样

**Comment by R-YaTian** [comment]
> 我的字典不就是E0509吗……
> 话说您是这边（怡山校区/至诚学院）的学生？

要是早点看到这个项目，我就不用花这么多时间提取字典了，欲哭无泪啊

**Comment by UMRnInside** [comment]
emmmmm......
你可以提取一下V7.10 E0310的字典。
那个是Windows 7/8/10 x64的。
话说你现在把`njit8021xclient`安装到哪里？

**Comment by R-YaTian** [comment]
> emmmmm......
> 你可以提取一下V7.10 E0310的字典。
> 那个是Windows 7/8/10 x64的。
> 话说你现在把`njit8021xclient`安装到哪里？

我就是Win10x64，我昨天提取的字典和你的对比了下，是一样的，甚至连提取过程中遇到的edi问题，都和你一模一样，他的值就是10

**Comment by R-YaTian** [comment]
> emmmmm......
> 你可以提取一下V7.10 E0310的字典。
> 那个是Windows 7/8/10 x64的。
> 话说你现在把`njit8021xclient`安装到哪里？

我现在打算装到路由器上，但是我自己搭的编译环境似乎出了点问题，死活编译不了，你能帮帮忙，救救孩子吧

**Comment by UMRnInside** [comment]
我记得有些同学的版本是V7.10来着……
[OpenWRT Makefile](https://github.com/UMRnInside/njit8021xclient/blob/master/Makefile)
这个是给 OpenWRT 使用的Makefile。
过程可以参考 https://imlonghao.com/37.html

**Comment by UMRnInside** [comment]
OpenWRT版本？还是别的固件？
CPU呢？
“死活编译不了” 有报错吗？

**Comment by R-YaTian** [comment]
> OpenWRT版本？还是别的固件？
> CPU呢？
> “死活编译不了” 有报错吗？

Openwrt的
cpu mt7620
有的
大佬能加个扣扣吗

**Comment by UMRnInside** [comment]
OK
253960216@qq.com
